//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 The Koordinator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterferenceDetectionRule) DeepCopyInto(out *InterferenceDetectionRule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterferenceDetectionRule.
func (in *InterferenceDetectionRule) DeepCopy() *InterferenceDetectionRule {
	if in == nil {
		return nil
	}
	out := new(InterferenceDetectionRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InterferenceDetectionRule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterferenceDetectionRuleList) DeepCopyInto(out *InterferenceDetectionRuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InterferenceDetectionRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterferenceDetectionRuleList.
func (in *InterferenceDetectionRuleList) DeepCopy() *InterferenceDetectionRuleList {
	if in == nil {
		return nil
	}
	out := new(InterferenceDetectionRuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InterferenceDetectionRuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterferenceDetectionRuleSpec) DeepCopyInto(out *InterferenceDetectionRuleSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterferenceDetectionRuleSpec.
func (in *InterferenceDetectionRuleSpec) DeepCopy() *InterferenceDetectionRuleSpec {
	if in == nil {
		return nil
	}
	out := new(InterferenceDetectionRuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterferenceDetectionRuleStatus) DeepCopyInto(out *InterferenceDetectionRuleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterferenceDetectionRuleStatus.
func (in *InterferenceDetectionRuleStatus) DeepCopy() *InterferenceDetectionRuleStatus {
	if in == nil {
		return nil
	}
	out := new(InterferenceDetectionRuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterferenceMetricCheckpoint) DeepCopyInto(out *InterferenceMetricCheckpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterferenceMetricCheckpoint.
func (in *InterferenceMetricCheckpoint) DeepCopy() *InterferenceMetricCheckpoint {
	if in == nil {
		return nil
	}
	out := new(InterferenceMetricCheckpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InterferenceMetricCheckpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterferenceMetricCheckpointList) DeepCopyInto(out *InterferenceMetricCheckpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InterferenceMetricCheckpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterferenceMetricCheckpointList.
func (in *InterferenceMetricCheckpointList) DeepCopy() *InterferenceMetricCheckpointList {
	if in == nil {
		return nil
	}
	out := new(InterferenceMetricCheckpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InterferenceMetricCheckpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterferenceMetricCheckpointSpec) DeepCopyInto(out *InterferenceMetricCheckpointSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterferenceMetricCheckpointSpec.
func (in *InterferenceMetricCheckpointSpec) DeepCopy() *InterferenceMetricCheckpointSpec {
	if in == nil {
		return nil
	}
	out := new(InterferenceMetricCheckpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InterferenceMetricCheckpointStatus) DeepCopyInto(out *InterferenceMetricCheckpointStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InterferenceMetricCheckpointStatus.
func (in *InterferenceMetricCheckpointStatus) DeepCopy() *InterferenceMetricCheckpointStatus {
	if in == nil {
		return nil
	}
	out := new(InterferenceMetricCheckpointStatus)
	in.DeepCopyInto(out)
	return out
}
