# permissions for end users to view interferencedetectionrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: interferencedetectionrule-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: koordetector
    app.kubernetes.io/part-of: koordetector
    app.kubernetes.io/managed-by: kustomize
  name: interferencedetectionrule-viewer-role
rules:
- apiGroups:
  - interference.koordinator.sh
  resources:
  - interferencedetectionrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - interference.koordinator.sh
  resources:
  - interferencedetectionrules/status
  verbs:
  - get
