---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - interference.koordinator.sh
  resources:
  - interferencedetectionrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - interference.koordinator.sh
  resources:
  - interferencedetectionrules/finalizers
  verbs:
  - update
- apiGroups:
  - interference.koordinator.sh
  resources:
  - interferencedetectionrules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - interference.koordinator.sh
  resources:
  - interferencemetriccheckpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - interference.koordinator.sh
  resources:
  - interferencemetriccheckpoints/finalizers
  verbs:
  - update
- apiGroups:
  - interference.koordinator.sh
  resources:
  - interferencemetriccheckpoints/status
  verbs:
  - get
  - patch
  - update
